### PR TITLE
Adding NumberInput

### LINKED ISSUE #3: Update the weight and percent form inputs to be number inputs
Create a `NumberInput` component. `TextInput` and `NumberInput` should share styles. Make `NumberInput` and `TextInput` be wrappers for `Input` but with different types.

### PR DESCRIPTION
**Pull request by ielixirz**
resolves tarikhamilton/one-rep-max#3

- Adding NumberInput component
- Replace TextInput with NumberInput component for weight field

### CODE REVIEW

**Comment by tarikhamilton** [comment]
To link the issue, you have to use one of these [keywords](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword). 

This is a good start, but I would like it taken one step further. You could create an `Input` component that both `TextInput` and `NumberInput` would import and use as the base. This way all of those CSS classes can be updated from one component.

**Comment by ielixirz** [comment]
> To link the issue, you have to use one of these [keywords](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
> 
> This is a good start, but I would like it taken one step further. You could create an `Input` component that both `TextInput` and `NumberInput` would import and use as the base. This way all of those CSS classes can be updated from one component.

Ok I got you, will work more on this.

**Comment by ielixirz** [comment]
@tarikhamilton I have done some more work and also create the sub-directory to contain only Input components file.

**Comment by tarikhamilton** [comment]
> @tarikhamilton I have done some more work and also create the sub-directory to contain only Input components file.

Well done, man! One suggestion is that you could've removed className here `className={className} {...props}` because it would've gotten spread in with props. I will leave it though because it is conveniently set up for concatenation with more classes in the future. Maybe that was your intent :)

Thank you for contributing!

**Pull request merged**
